spring:
  application:
    name: springboot_study_demo

  datasource:
    username: root
    password: xxxxxx
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false  # 关闭模板引擎的缓存

  messages:
    basename: i18n.login  # 国际化配置文件的地址

  mvc:
    format:
      date: yyyy-MM-dd  # 时间日期格式化

server:
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzq.springboot_study_demo.pojo
  configuration:
    map-underscore-to-camel-case: true
